/** All module names used for permission matrices (user + role defaults). */
export const ALL_MODULE_NAMES = [
  'Dashboard',
  'Users',
  'Reports',
  'Assets',
  'My Assets',
  'Asset List',
  'Asset Assignment',
  'Asset Request',
  'Request Management',
  'Asset Tagging',
  'Asset Transfer',
  'Asset Maintenance',
  'Asset Repair',
  'Asset Return',
  'Return Request',
  'Transfer Request',
  'Asset Disposal',
  'Asset Borrowing',
  'Borrow Request Management',
  'Asset History',
  'Assignment History',
  'Transfer History',
  'Maintenance History',
  'Repair History',
  'Return History',
  'Borrow History',
  'Asset Request History',
  'Disposal History',
  'Audit Trail',
  'Forms',
  'Accountability Form',
  'Checklist Form',
  'Borrow Form',
  'Return Form',
  'Transfer Form',
  'Approvals',
  'Settings',
  'Asset Categories',
  'Asset Types',
  'Asset Brands',
  'Suppliers',
  'Departments',
  'Locations',
  'Roles',
  'Companies',
] as const;
