export type AuditStatus = 'success' | 'failure';

export type AuditSeverity = 'info' | 'warning' | 'critical';

/**
 * Canonical action strings actually written to `audit_logs.action`.
 * Mixed snake_case (workflow-style events) and human-readable labels
 * (CRUD-style events) match what controllers/services record today.
 */
export const auditActions = [
  // Assets
  'Created Asset',
  'Updated Asset',
  'Deleted Asset',
  'Imported Asset',
  'Assigned Asset',
  'Reassigned Asset',
  'Returned Asset',
  'Returned Asset for Transfer',
  'Returned for Transfer',
  'Transferred Asset',
  'Transferred Asset to Company',
  'Transferred',
  'Created Asset Assignment',
  'Updated Asset Assignment',
  'Deleted Asset Assignment',
  // Asset builders
  'Created Asset Builder',
  'Updated Asset Builder',
  'Updated Asset Builder Status',
  'Deleted Asset Builder',
  'Added to Asset Builder',
  'Added to Builder',
  'Removed from Asset Builder',
  'Assigned Asset Builder',
  'Asset Builder Returned',
  'Transferred Asset Builder to Company',
  // Asset checks / returns / transfers / borrow / requests
  'Created Asset Checklist',
  'Created Return Offboarding Checklist',
  'Signed Asset Checklists',
  'Received Asset Checklists',
  'Created Asset Transfer Form',
  'Signed Asset Transfer Form',
  'Declined Asset Transfer Form',
  'Submitted Return Request',
  'Created Asset Return Form',
  'Signed Asset Return Form',
  'Declined Asset Return Form',
  'Declined Asset Return Form (processor)',
  'Processed Asset Return Form (Processor)',
  'Assign to Processor on Return',
  'Assigned to Processor on Return',
  'create_borrow_request',
  'approve_borrow_request_dept_head',
  'approve_borrow_request_staff',
  'decline_borrow_request_dept_head',
  'decline_borrow_request_staff',
  'receive_borrow_request',
  'process_borrow_return',
  'create_asset_request',
  'approve_asset_request',
  'reject_asset_request',
  'delete_asset_request',
  // Accountability forms
  'Created Accountability Form',
  'Signed Accountability Form',
  'Declined Accountability Form',
  'Deleted Accountability Form',
  'Disabled Accountability Form',
  'Re-enabled Accountability Form',
  'Signed Received Copy for 201 File',
  // Intangible assets
  'Created Intangible Asset',
  'Created Intangible Assets (Bulk)',
  'Updated Intangible Asset',
  'Assigned Intangible Asset',
  'Unassigned Intangible Asset',
  'Transferred Intangible Asset',
  'Returned Intangible Asset',
  'Requested Return of Intangible Asset',
  // Reference data
  'Created Brand',
  'Updated Brand',
  'Deleted Brand',
  'Created Category',
  'Updated Category',
  'Deleted Category',
  'Created Type',
  'Updated Type',
  'Deleted Type',
  'Created Supplier',
  'Updated Supplier',
  'Deleted Supplier',
  'Created Department',
  'Updated Department',
  'Deleted Department',
  'Created Location',
  'Updated Location',
  'Deleted Location',
  'Created Position',
  'Updated Position',
  'Deleted Position',
  'Created Risk Level',
  'Updated Risk Level',
  'Deleted Risk Level',
  'Created Intangible Asset Type',
  'Updated Intangible Asset Type',
  'Deleted Intangible Asset Type',
  'create_department',
  'update_department',
  'delete_department',
  'create_location',
  'update_location',
  'delete_location',
  'create_position',
  'update_position',
  'delete_position',
  // Companies
  'Created Company',
  'Updated Company',
  'Deleted Company',
  'Set Active Company',
  'Set Main Company',
  'Deleted Company Logo',
  // Users / roles / permissions
  'User Registration',
  'Created User',
  'Updated User',
  'Deleted User',
  'create_user',
  'update_user',
  'delete_user',
  'remove_user_lockout',
  'change_user_password',
  'Created Role',
  'Updated Role',
  'Deleted Role',
  'create_role',
  'update_role',
  'delete_role',
  'Created Permission',
  'Updated Permission',
  'Deleted Permission',
  'Updated Role Permissions',
  'Updated User Permissions',
  'Applied Role Permissions',
  // Auth
  'auth.login.success',
  'auth.login.failure',
  'auth.logout',
  'Auto Logout',
  'Session Revoked',
  'Password Reset Requested',
  'Password Reset',
  'Password Changed',
  'Password Changed (Forced)',
  'MFA Enabled',
  'MFA Disabled',
  'MFA Backup Codes Regenerated',
  'Profile Updated',
  'Avatar Updated',
  // Settings
  'settings.updated',
  'update_asset_id_format_settings',
  'update_accountability_form_settings',
  'update_asset_return_form_settings',
  'update_asset_checklist_form_settings',
  'update_asset_transfer_form_settings',
  'update_asset_borrow_form_settings',
  'copy_main_company_asset_settings',
  'copy_main_company_location_settings',
  'copy_main_company_department_settings',
  'Updated Global MFA Setting',
  'Updated Security Settings',
  'Created Setting',
  'Updated Setting',
  'Deleted Setting',
  // Audit
  'audit.exported',
  'audit.logs_archived',
  'settings.audit_retention.created',
  'settings.audit_retention.updated',
  // Migrations
  'run_migrations',
  'rollback_migration',
  'create_migration',
  // Notifications
  'Created Notification',
  'Updated Notification',
  'Deleted Notification',
  'mark_notification_as_read',
  'mark_all_notifications_as_read',
  'clear_notification',
  'clear_all_notifications',
  'send_unsigned_accountability_notification',
  // Gate passes
  'Created Gate Pass',
  'Updated Gate Pass',
  'Deleted Gate Pass',
] as const;

export type AuditAction = (typeof auditActions)[number];

/**
 * Canonical resource-type strings actually written to
 * `audit_logs.resource_type`.
 */
export const auditResourceTypes = [
  'asset',
  'asset_assignment',
  'asset_builder',
  'asset_checklist',
  'asset_return',
  'asset_return_form',
  'asset_transfer',
  'asset_transfer_form',
  'asset_request',
  'borrow_request',
  'accountability_form',
  'accountability-form',
  'gate_pass',
  'intangible_asset',
  'intangible_asset_type',
  'risk_level',
  'user',
  'role',
  'permission',
  'role_permissions',
  'user_permissions',
  'setting',
  'settings',
  'company',
  'department',
  'location',
  'brand',
  'category',
  'type',
  'supplier',
  'position',
  'notification',
  'migration',
  'audit_log',
  'audit_logs',
  'audit_retention_settings',
  'auth',
  'auth_session',
  'asset-assignment',
  'asset-builder',
] as const;

export type AuditResourceType = (typeof auditResourceTypes)[number];
