// Shared types index file - export all types for easy importing
export * from './common';
export * from './dtos';
export * from './audit';

// Re-export common types for convenience
export type {
  ValidationError,
  ApiResponse,
  PaginationParams,
  BaseEntity,
  AssetStatus,
  AssetCondition,
  MaintenanceSchedule,
  DepreciationMethod,
  AssignmentStatus,
  AccountabilityFormStatus,
  UserRole,
  AssetType,
  ManagerRole,
  UserPermissions,
} from './common';

// Re-export DTO types for convenience
export type {
  CreateAssetDto,
  UpdateAssetDto,
  AssetResponseDto,
  AssetChildDto,
  AssetListResponseDto,
  AssetDocumentDto,
  AssetAssignmentDto,
  AccountabilityFormDto,
  UserDto,
  UpdateUserDto,
  UserResponseDto,
  UserListResponseDto,
  RoleResponseDto,
  RoleListResponseDto,
  DepartmentResponseDto,
  DepartmentListResponseDto,
  CompanyResponseDto,
  CompanyListResponseDto,
  CreateLocationDto,
  UpdateLocationDto,
  CreateLocationRoomDto,
  UpdateLocationRoomDto,
  LocationResponseDto,
  LocationRoomResponseDto,
  LocationListResponseDto,
  CreateCategoryDto,
  UpdateCategoryDto,
  CategoryResponseDto,
  CategoryListResponseDto,
  CreateTypeDto,
  UpdateTypeDto,
  TypeResponseDto,
  TypeListResponseDto,
  CreateSupplierDto,
  UpdateSupplierDto,
  SupplierResponseDto,
  SupplierListResponseDto,
  CreateBrandDto,
  UpdateBrandDto,
  BrandResponseDto,
  BrandListResponseDto,
  CreatePositionDto,
  UpdatePositionDto,
  PositionResponseDto,
  PositionListResponseDto,
  LoginDto,
  RegisterDto,
  VerifyOTPDto,
  ForgotPasswordDto,
  ResetPasswordDto,
  ChangePasswordDto,
  UpdateProfileDto,
  UserPermissionsDto,
  AuditLogResponseDto,
  AuditLogListResponseDto,
  SettingsDto,
  SettingsListResponseDto,
  MFALoginResponse,
  MFAVerifyDto,
  MFASetupResponse,
  MFASetupVerifyDto,
  MFADisableDto,
  MFABackupCodesResponse,
} from './dtos';

export type {
  AuditStatus,
  AuditSeverity,
  AuditAction,
  AuditResourceType,
} from './audit';
